spring:
  jpa:
    show-sql: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
